### PR TITLE
Delete or Update Editorial bot comments when violations are fixed

### LINKED ISSUE #469: When description is updated, we should remove the bot comment asking for a description
We should use a marker similar to how we did it for some other things.

Given the comment is used for all sorts of editorial rules, we should reevaluate the rules and update/hide the comment accordingly.

### PR DESCRIPTION
**Pull request by ayagmar**
Fix #469 Handle Edited events to modify or delete bot comments if violations are updated
I have tested this on my gh bot fork and everything works as expected

Comment edited when I fixed one violation : 
{0590EEA4-9B09-4425-ADA5-DB62E88F916D}
Comment is removed when I fixed all violations 
{1501C552-A401-4C29-8F49-ABA1CF2F0330}

Thanks!

### CODE REVIEW

File: src/main/java/io/quarkus/bot/CheckIssueEditorialRules.java [hunk 1]
```diff
@@ -1,25 +1,23 @@
 package io.quarkus.bot;
 
-import java.io.IOException;
```
Comment (ayagmar) [inline src/main/java/io/quarkus/bot/CheckIssueEditorialRules.java:3]: my IDE automatically changed the import order, I can restore this if not accepted

**Comment by ayagmar** [comment]
Hello @gsmet 
When you have the time could you please take a look at this PR and let me know if you want any changes ?
Thanks

**Comment by ayagmar** [comment]
ping @gsmet

**Comment by gsmet** [comment]
Hey there,

Thanks for the pull request, I will have a look :).

File: src/main/java/io/quarkus/bot/GitHubBotActions.java [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+                LOG.debug("Pull request #" + pullRequest.getNumber() + " - Updated title to: " + newTitle);
+            } catch (IOException e) {
+                LOG.error(String.format("Pull Request #%s - Failed to update title", pullRequest.getNumber()), e);
+            }
+        } else {
+            LOG.info("Pull request #" + pullRequest.getNumber() + " - Update title to: " + newTitle);
+        }
+    }
+
+    public Optional<GHIssueComment> findBotComment(GHPullRequest pullRequest) throws IOException {
```
Comment (gsmet) [inline src/main/java/io/quarkus/bot/GitHubBotActions.java]: I would pass the marker as another parameter here.

File: src/main/java/io/quarkus/bot/GitHubBotActions.java [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+
+import io.quarkus.bot.config.QuarkusGitHubBotConfig;
+import io.quarkus.bot.util.Strings;
+
+/**
+ * This class handles all GitHub operations related to bot actions.
+ * It provides methods for adding, updating, and removing comments on pull requests,
+ * as well as setting pull request titles.
+ */
+@RequestScoped
```
Comment (gsmet) [inline src/main/java/io/quarkus/bot/GitHubBotActions.java]: I would avoid using `@RequestScoped` here. Could you use `@Singleton` instead?

File: src/main/java/io/quarkus/bot/GitHubBotActions.java [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+class GitHubBotActions {
```
Comment (gsmet) [inline src/main/java/io/quarkus/bot/GitHubBotActions.java:20]: I wonder if it would make more sense to repurpose `GHIssues` and `GHPullRequests` as (`@Singleton`) CDI beans and move the these methods there?

WDYT?

File: src/main/java/io/quarkus/bot/CheckPullRequestEditorialRules.java [hunk 5]
```diff
@@ -1,43 +1,39 @@
...
 import java.util.List;
-import java.util.Locale;
-import java.util.regex.Pattern;
+import java.util.Optional;
+import java.util.StringJoiner;
 
 import jakarta.inject.Inject;
 
-import org.jboss.logging.Logger;
+import org.apache.commons.lang3.StringUtils;
```
Comment (gsmet) [inline src/main/java/io/quarkus/bot/CheckPullRequestEditorialRules.java]: Let's not depend on a class just for an empty string constant :).

File: src/main/java/io/quarkus/bot/violation/ViolationDetectorManager.java [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+import java.util.stream.Collectors;
+
+import jakarta.enterprise.context.RequestScoped;
+
+import org.kohsuke.github.GHPullRequest;
+
+/**
+ * Manager for all violation detectors.
+ */
+@RequestScoped
```
Comment (gsmet) [inline src/main/java/io/quarkus/bot/violation/ViolationDetectorManager.java]: Please make it `@Singleton` as it doesn't have any request scope.

**Review by gsmet — COMMENTED** [review]
Thanks, it looks really good and I see you added tests which is great.

I added a few comments.

Also, could you please rebase and run a full build to get the imports sorted. I somehow forgot to set up the impsort-maven-plugin when I created the project.

Let me know if you have any questions and don't hesitate to push back if something in my comments seems off.

File: src/main/java/io/quarkus/bot/GitHubBotActions.java (hunk 4 above)
Comment (ayagmar) [reply src/main/java/io/quarkus/bot/GitHubBotActions.java:20]: Hmm makes sense and does separate concerns a bit, Ill push a commit and let me know what u think

File: src/main/java/io/quarkus/bot/CheckPullRequestEditorialRules.java (hunk 5 above)
Comment (ayagmar) [reply src/main/java/io/quarkus/bot/CheckPullRequestEditorialRules.java]: I need to get rid of this bad habit

**Comment by ayagmar** [comment]
Hello @gsmet Thanks for the review, I have made some changes and fixed the formatting, let me know what you think

**Comment by abdeslam-agmar-nw** [comment]
@gsmet bump

**Comment by ayagmar** [comment]
@gsmet bump

**Comment by ayagmar** [comment]
ping @gsmet , are there any pending actions?

**Review by gsmet — APPROVED** [review]
Sorry about that, let's merge and we can tweak things later if need be!

**Comment by ayagmar** [comment]
> Sorry about that, let's merge and we can tweak things later if need be!

Great, please ping me in case there are any issues or refinements to be made, I'll take care of it
